@extends('dashboardlayout')

@section('title', 'Report')

@section('report', 'active')

@section('content')

<style>
#company-report-table .th,  #driver-report-table .th {
    border-bottom-width: 1px;
    font-size: 1rem !important;
    font-weight: bold;
    color: red;
}

.icons-option a{
  padding: 5px;
}

.form-group.required .control-label:after { 
    color: #d00;
    content: "*";
    position: absolute;
    margin-left: 8px;
    top:7px;
    font-family: 'FontAwesome';
    font-weight: normal;
    font-size: 14px;
    content: "\f069";
}
</style>

<div class="panel-header panel-header-sm">
</div>
<div class="content">
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <h4 class="card-title">COMPANY REPORT</h4>
          <p class="category">These module is for Billing Report functions of Company.</p>
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <div class="row">
              <div class="col">
                <span class="float-right"><button type="button" id="btnModalShow" onclick="showReportGenerateModal('Generate Company Report', '', 'company')" class="btn btn-primary"><i class="fa-solid fa-plus"></i></button></span>
                </div>
            </div>
                  <table class="table table-bordered" id="company-report-table">
                      <thead class="table-bordered">
                        <th class="th">Generated Date</th>
                        <th class="th">Period</th>
                        <th class="th">Generated By</th>
                        <th class="th" data-orderable="false">Action</th>
                        <!-- <th class="th">Source</th>
                        <th class="th">Destination</th>
                        <th class="th">Distance</th>
                        <th class="th" >Weight</th>
                        <th class="th">Rate</th>
                        <th class="th">Bill</th>
                        <th class="th">Date</th> -->
                      </thead>
                </table>
                  </div>
          </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <h4 class="card-title">DRIVER REPORT</h4>
          <p class="category">These module is for Billing Report functions of Driver.</p>
        </div>
        <div class="card-body">
          <div class="table-responsive">
          <div class="row">
              <!-- <div class="col"> -->
                  <!-- <div class="row">
                     <div class="col">
                          <div class="form-group">
                              <label for="formGroupExampleInput2" class="control-label font-weight-bold">From:</label>
                              <input type="date" class="form-control form-control-lg" id="date" name="date" value="" >
                          </div>   
                      </div>
                      <div class="col">
                          <div class="form-group">
                              <label for="formGroupExampleInput2" class="control-label font-weight-bold">To:</label>
                              <input type="date" class="form-control form-control-lg" id="date" name="date" value="" >
                          </div>   
                      </div>
                  </div> 
                </div> -->
              <div class="col">
              <span class="float-right"><button type="button" id="btnModalShow" onclick="showReportGenerateModal('Generate Driver Report', '', 'driver')" class="btn btn-primary"><i class="fa-solid fa-plus"></i></button></span>
              </div>
            </div>
                  <table class="table table-bordered" id="driver-report-table">
                      <thead class="table-bordered">
                        <th class="th">Generated Date</th>
                        <th class="th">Period</th>
                        <th class="th">Generated By</th>
                        <th class="th" data-orderable="false">Action</th>
                      </thead>
                </table>
            </div>
          </div>
      </div>
    </div>
  </div>
</div>

<div class="content">
  
</div>

@include("report.modal_report_generate")
@endsection

@section("scripts")

<script>
//   $(document).ready(function(){
//     $('#formReportGenerate').submit(function(e) {
//       e.preventDefault();
//         var from = $("#dateFrom").val();
//         var to = $("#to").val();
//         var id = $("#reportID").val();

//         //var formatedDate = generateDateRangeLink(from, to);
//         ;
//         linkReport += "/" + from + "/"  + id;
//         alert(linkReport);
//         $("#formReportGenerate").attr('action', linkReport);
//         return false;
//     });
// });
  
//   $("#btnModalShow").click(function(){
//   //alert("Hellow");
//   // ("#refID").val("");
//   // $("#item").val("");
//   // $("#quantity").val("");
//   // $("#accumulated_total").val("");
//   // $("#entry_by").val("");
//   // $("#dateInput").val("");
//   // $("#modalTitle").html("Add Expense");
//   // $("#modalBtnSubmit").show();
//   // $("#modalBtnUpdate").hide();
    
// });
initiliazedReportFeatures();
</script>


<script src="{{asset('/js/globalFunctions.js')}}"></script>

@endsection